// Profile admin metadata
export const PROFILE_ADMIN = {
  name: 'Aïsha Okafor',
  role: 'Operations Admin',
  roleTag: 'ops',
  email: 'aisha@atlas.example',
  phone: '+1 (313) 555-0142',
  location: 'Detroit, MI · USA',
  joinedDate: 'Mar 4, 2024',
} as const;

// Quick stats
export const PROFILE_QUICKSTATS = [
  {
    label: 'Two-factor auth',
    value: 'Enabled',
    meta: 'Authenticator · since Apr 12',
    status: 'ok',
  },
  {
    label: 'IP allowlist',
    value: '3 addresses',
    meta: 'Strict mode · last edit 2w ago',
    status: 'ok',
  },
  {
    label: 'Last sign-in',
    value: 'Today, 9:15 AM',
    meta: '71.82.45.12 · Detroit · Chrome',
    status: 'default',
  },
  {
    label: 'Actions today',
    value: '7',
    meta: 'All audit-logged',
    status: 'default',
  },
] as const;

// Banner data
export const PROFILE_BANNERS = [
  {
    id: 'password-due',
    title: 'Password reset due in 12 days',
    text: 'Atlas requires admins to reset passwords every 90 days. Last reset: Jan 30, 2026. After Apr 30 + 12 days, you\'ll be required to reset before your next sign-in.',
  },
] as const;

// Permissions domains
export const PERMISSIONS_DOMAINS = [
  {
    id: 'users',
    name: 'Users',
    icon: 'users',
    summary: { allowed: 4, total: 5, label: 'actions allowed' },
    rows: [
      {
        id: 'users.view',
        name: 'View all users',
        note: 'See profiles, hires, and engagement history across the platform',
        status: 'allowed',
        badge: 'Allowed',
      },
      {
        id: 'users.suspend',
        name: 'Suspend accounts',
        note: 'Temporarily disable candidate or client accounts',
        status: 'allowed',
        badge: 'Allowed',
      },
      {
        id: 'users.ban',
        name: 'Ban accounts',
        note: 'Permanently remove platform access (admin discretion required)',
        status: 'allowed',
        badge: 'Allowed',
      },
      {
        id: 'users.modify',
        name: 'Modify user profiles',
        note: 'Edit candidate or client information when authorized',
        status: 'allowed',
        badge: 'Allowed',
      },
      {
        id: 'users.create-admin',
        name: 'Create new admins',
        note: 'Reserved for Super Admin — required for sensitive privilege escalation',
        status: 'restricted',
        badge: 'Super only',
      },
    ],
  },
  {
    id: 'operations',
    name: 'Operations',
    icon: 'operations',
    summary: { allowed: 5, total: 5, label: 'actions allowed · primary domain' },
    rows: [
      {
        id: 'ops.engagements',
        name: 'Manage engagements',
        note: 'View and intervene in active client/candidate contracts',
        status: 'allowed',
        badge: 'Allowed',
      },
      {
        id: 'ops.disputes',
        name: 'Manage disputes',
        note: 'Resolve, escalate, or refund based on dispute investigation',
        status: 'allowed',
        badge: 'Allowed',
      },
      {
        id: 'ops.jobs',
        name: 'Manage job postings',
        note: 'Approve, edit, archive job posts',
        status: 'allowed',
        badge: 'Allowed',
      },
      {
        id: 'ops.reviews',
        name: 'Review specialist work',
        note: 'Audit reviews completed by Talent Specialists',
        status: 'allowed',
        badge: 'Allowed',
      },
      {
        id: 'ops.reports',
        name: 'Generate reports',
        note: 'Custom reports across operational dimensions',
        status: 'allowed',
        badge: 'Allowed',
      },
    ],
  },
  {
    id: 'trust-safety',
    name: 'Trust & Safety',
    icon: 'trust-safety',
    summary: { allowed: 4, total: 4, label: 'actions allowed' },
    rows: [
      {
        id: 'ts.fraud',
        name: 'Investigate fraud',
        note: 'Open and conduct investigations on flagged accounts',
        status: 'allowed',
        badge: 'Allowed',
      },
      {
        id: 'ts.incidents',
        name: 'Handle security incidents',
        note: 'Respond to and document security events',
        status: 'allowed',
        badge: 'Allowed',
      },
      {
        id: 'ts.suspicious',
        name: 'Monitor suspicious activity',
        note: 'Review trust signals across the user base',
        status: 'allowed',
        badge: 'Allowed',
      },
      {
        id: 'ts.protective',
        name: 'Take protective action',
        note: 'Suspend or ban accounts based on T&S findings',
        status: 'allowed',
        badge: 'Allowed',
      },
    ],
  },
  {
    id: 'finance',
    name: 'Finance',
    icon: 'finance',
    summary: { allowed: 2, partial: 1, restricted: 2, label: 'allowed · 1 limited' },
    rows: [
      {
        id: 'fin.transactions',
        name: 'View transactions',
        note: 'Read access to all financial transactions',
        status: 'allowed',
        badge: 'Allowed',
      },
      {
        id: 'fin.refunds',
        name: 'Issue refunds',
        note: 'Allowed up to $1,000; above that requires Super Admin approval',
        status: 'limited',
        badge: 'Limited',
      },
      {
        id: 'fin.payouts',
        name: 'Process payouts',
        note: 'Reserved for Finance Admin',
        status: 'restricted',
        badge: 'Finance only',
      },
      {
        id: 'fin.fees',
        name: 'Modify platform fees',
        note: 'Reserved for Super Admin',
        status: 'restricted',
        badge: 'Super only',
      },
      {
        id: 'fin.subscriptions',
        name: 'Adjust subscriptions',
        note: 'Reserved for Finance Admin',
        status: 'restricted',
        badge: 'Finance only',
      },
    ],
  },
  {
    id: 'compliance',
    name: 'Compliance',
    icon: 'compliance',
    summary: { allowed: 1, total: 5, label: 'actions allowed · read-only access' },
    rows: [
      {
        id: 'comp.audit',
        name: 'View audit logs',
        note: 'Read access only — logs are immutable for all roles',
        status: 'allowed',
        badge: 'Read only',
      },
      {
        id: 'comp.legal',
        name: 'Handle legal requests',
        note: 'Reserved for Compliance Admin',
        status: 'restricted',
        badge: 'Compliance only',
      },
      {
        id: 'comp.dsr',
        name: 'Process data subject rights',
        note: 'GDPR, CCPA, PIPEDA requests — reserved for Compliance Admin',
        status: 'restricted',
        badge: 'Compliance only',
      },
      {
        id: 'comp.modify-audit',
        name: 'Modify audit logs',
        note: 'Immutable for everyone — including Super Admin',
        status: 'restricted',
        badge: 'Immutable',
      },
      {
        id: 'comp.regulatory',
        name: 'Submit regulatory reports',
        note: 'Reserved for Compliance Admin',
        status: 'restricted',
        badge: 'Compliance only',
      },
    ],
  },
  {
    id: 'platform',
    name: 'Platform',
    icon: 'platform',
    summary: { allowed: 1, total: 5, label: 'actions allowed · read-only' },
    rows: [
      {
        id: 'plat.view',
        name: 'View platform settings',
        note: 'Read-only visibility into Atlas configuration',
        status: 'allowed',
        badge: 'Read only',
      },
      {
        id: 'plat.modify',
        name: 'Modify platform settings',
        note: 'Reserved for Super Admin',
        status: 'restricted',
        badge: 'Super only',
      },
      {
        id: 'plat.categories',
        name: 'Modify categories & skills',
        note: 'Reserved for Super Admin',
        status: 'restricted',
        badge: 'Super only',
      },
      {
        id: 'plat.integrations',
        name: 'Manage integrations',
        note: 'Stripe, Wise, SendGrid — reserved for Super Admin',
        status: 'restricted',
        badge: 'Super only',
      },
      {
        id: 'plat.templates',
        name: 'Edit email & SMS templates',
        note: 'Reserved for Super Admin',
        status: 'restricted',
        badge: 'Super only',
      },
    ],
  },
  {
    id: 'internal',
    name: 'Internal',
    icon: 'internal',
    summary: { allowed: 2, total: 4, label: 'actions allowed' },
    rows: [
      {
        id: 'int.dashboards',
        name: 'View performance dashboards',
        note: 'Internal analytics across team',
        status: 'allowed',
        badge: 'Allowed',
      },
      {
        id: 'int.read-incidents',
        name: 'Read incident reports',
        note: 'Read access to internal incident archive',
        status: 'allowed',
        badge: 'Allowed',
      },
      {
        id: 'int.file-incidents',
        name: 'File incident reports',
        note: 'Reserved for Talent Specialists who run point on incident response',
        status: 'restricted',
        badge: 'Specialists',
      },
      {
        id: 'int.manage-admins',
        name: 'Manage other admins',
        note: 'Modify roles, permissions, IP allowlists — Super Admin only',
        status: 'restricted',
        badge: 'Super only',
      },
    ],
  },
] as const;

// Activity timeline
export const ACTIVITY_TIMELINE_DATA = {
  summary: { today: 7, thisMonth: 248 },
  filters: [
    { id: 'all', label: 'All', count: 248 },
    { id: 'suspension', label: 'Suspensions', count: 12 },
    { id: 'refund', label: 'Refunds', count: 34 },
    { id: 'dispute', label: 'Disputes', count: 87 },
    { id: 'override', label: 'Overrides', count: 3 },
    { id: 'export', label: 'Exports', count: 11 },
    { id: 'signin', label: 'Sign-ins', count: 42 },
  ],
  entries: [
    {
      day: 'Today',
      date: 'April 30, 2026',
      count: 7,
      activities: [
        {
          time: '12:34 PM',
          category: 'suspension',
          verb: 'Suspended candidate',
          target: 'Marcus T.',
          targetTwo: '',
          detail: 'Repeated profile fraud — 3 strikes',
          outcome: 'Action taken',
          outcomeStatus: 'success',
          refId: 'SUS-2026-0218',
          tag: 'SUSPENSION',
        },
        {
          time: '11:52 AM',
          category: 'dispute',
          verb: 'Resolved dispute',
          target: 'DSP-2026-0481',
          targetTwo: '',
          detail: 'Resolved in client favor',
          outcome: 'Closed',
          outcomeStatus: 'success',
          refId: 'DSP-2026-0481',
          tag: 'DISPUTE',
        },
        {
          time: '11:08 AM',
          category: 'refund',
          verb: 'Approved refund of',
          target: '$850',
          targetTwo: 'Acme Holdings',
          detail: 'Service-level dispute resolution',
          outcome: 'Refunded via Stripe',
          outcomeStatus: 'success',
          refId: 'REF-2026-0102',
          tag: 'REFUND',
        },
        {
          time: '10:14 AM',
          category: 'ban',
          verb: 'Banned client',
          target: 'Acme Holdings',
          targetTwo: '',
          detail: 'Confirmed payment fraud after investigation',
          outcome: 'Account terminated',
          outcomeStatus: 'success',
          refId: 'BAN-2026-0019',
          tag: 'BAN',
        },
        {
          time: '9:42 AM',
          category: 'export',
          verb: 'Generated report',
          target: 'Disputes summary, April',
          targetTwo: '',
          detail: 'CSV export — 47 rows',
          outcome: 'Downloaded',
          outcomeStatus: 'success',
          refId: 'RPT-2026-0044',
          tag: 'EXPORT',
        },
        {
          time: '9:21 AM',
          category: 'investigation',
          verb: 'Closed investigation on',
          target: '3 linked candidates',
          targetTwo: '',
          detail: 'Determined: same-IP coordination, not credible fraud',
          outcome: 'No action',
          outcomeStatus: 'partial',
          refId: 'INV-2026-0177',
          tag: 'INVESTIGATION',
        },
        {
          time: '9:15 AM',
          category: 'signin',
          verb: 'Signed in from',
          target: 'Detroit, MI',
          targetTwo: '',
          detail: '71.82.45.12 · Chrome 124 · macOS 14.4',
          outcome: 'Verified · 2FA',
          outcomeStatus: 'success',
          refId: 'SES-2026-2204',
          tag: 'SIGN-IN',
        },
      ],
    },
    {
      day: 'Yesterday',
      date: 'April 29, 2026',
      count: 11,
      activities: [
        {
          time: '4:32 PM',
          category: 'dispute',
          verb: 'Resolved dispute',
          target: 'DSP-2026-0473',
          targetTwo: '',
          detail: 'Partial refund issued — both parties at fault',
          outcome: 'Partial',
          outcomeStatus: 'partial',
          refId: 'DSP-2026-0473',
          tag: 'DISPUTE',
        },
        {
          time: '3:14 PM',
          category: 'refund',
          verb: 'Approved refund of',
          target: '$250',
          targetTwo: 'Carlos R.',
          detail: 'Cancelled engagement before kickoff',
          outcome: 'Refunded',
          outcomeStatus: 'success',
          refId: 'REF-2026-0098',
          tag: 'REFUND',
        },
        {
          time: '2:08 PM',
          category: 'dispute',
          verb: 'Reviewed appeal from',
          target: 'Deniz K.',
          targetTwo: '',
          detail: 'Appealed earlier suspension — appeal declined',
          outcome: 'Closed',
          outcomeStatus: 'success',
          refId: 'APL-2026-0031',
          tag: 'APPEAL',
        },
        {
          time: '11:42 AM',
          category: 'suspension',
          verb: 'Suspended candidate',
          target: 'Lin W.',
          targetTwo: '',
          detail: 'Verification document fraud',
          outcome: 'Escalated to T&S',
          outcomeStatus: 'escalated',
          refId: 'SUS-2026-0212',
          tag: 'SUSPENSION',
        },
        {
          time: '9:08 AM',
          category: 'signin',
          verb: 'Signed in from',
          target: 'Detroit, MI',
          targetTwo: '',
          detail: '71.82.45.12 · Chrome 124 · macOS 14.4',
          outcome: 'Verified · 2FA',
          outcomeStatus: 'success',
          refId: 'SES-2026-2117',
          tag: 'SIGN-IN',
        },
      ],
    },
    {
      day: 'Apr 28, 2026',
      date: 'Apr 28, 2026',
      count: 5,
      activities: [
        {
          time: '5:18 PM',
          category: 'override',
          verb: 'Override approved for',
          target: 'Sarah K.',
          targetTwo: 'escalated case',
          detail: 'Authorized verification bypass after manual review',
          outcome: 'Escalated',
          outcomeStatus: 'escalated',
          refId: 'OVR-2026-0011',
          tag: 'OVERRIDE',
        },
        {
          time: '11:34 AM',
          category: 'export',
          verb: 'Generated report',
          target: 'T&S incident summary',
          targetTwo: '',
          detail: 'Q2 brief for Super Admin · 22 incidents',
          outcome: 'Sent',
          outcomeStatus: 'success',
          refId: 'RPT-2026-0042',
          tag: 'EXPORT',
        },
      ],
    },
  ],
  footerText: 'Showing 14 of 248 actions this month',
} as const;

// Account settings
export const ACCOUNT_SETTINGS_BLOCKS = [
  {
    id: 'identity',
    title: 'Identity',
    icon: 'identity',
    meta: 'Verified',
    rows: [
      {
        key: 'Email',
        value: 'aisha@atlas.example',
        badge: 'VERIFIED',
        action: 'Change',
        actionId: 'change-email',
      },
      {
        key: 'Phone',
        value: '+1 (313) 555-0142',
        badge: 'VERIFIED',
        action: 'Change',
        actionId: 'change-phone',
      },
      {
        key: 'Display name',
        value: 'Aïsha Okafor',
        action: 'Edit',
        actionId: 'edit-name',
      },
    ],
  },
  {
    id: 'security',
    title: 'Security',
    icon: 'security',
    meta: 'Strong',
    rows: [
      {
        key: 'Password',
        value: 'Last changed Jan 30, 2026 · Reset in 12 days',
        warning: true,
        action: 'Change',
        actionId: 'change-password',
        actionPrimary: true,
      },
      {
        key: 'Two-factor authentication',
        value: 'Authenticator app · enrolled Apr 12, 2026',
        badge: 'ENABLED',
        action: 'Manage',
        actionId: 'manage-2fa',
      },
      {
        key: 'Backup codes',
        value: '6 of 8 remaining · last used Apr 14',
        action: 'Regenerate',
        actionId: 'regen-backup',
      },
    ],
  },
  {
    id: 'ip-allowlist',
    title: 'IP Allowlist',
    icon: 'ip-allowlist',
    meta: 'Strict mode',
    rows: [
      {
        key: 'Allowed addresses',
        isList: true,
        items: [
          { ip: '192.168.10.42', label: 'Office (primary)' },
          { ip: '192.168.10.43', label: 'Office (backup)' },
          { ip: '2001:db8::1', label: 'Home VPN' },
        ],
        action: 'Edit list',
        actionId: 'edit-allowlist',
      },
      {
        key: 'Enforcement mode',
        value: 'Strict — sign-in blocked from non-allowlisted IPs',
        action: 'Change',
        actionId: 'change-enforcement',
      },
    ],
  },
  {
    id: 'notifications',
    title: 'Notifications',
    icon: 'notifications',
    meta: '5 of 7 on',
    rows: [
      {
        key: 'Critical alerts (urgent)',
        value: 'Email + SMS for fraud, legal, security incidents',
        toggle: true,
        toggled: true,
      },
      {
        key: 'SLA breaches',
        value: 'Email when disputes or reviews exceed SLA',
        toggle: true,
        toggled: true,
      },
      {
        key: 'Daily digest',
        value: 'Summary of platform activity, sent 9:00 AM',
        toggle: true,
        toggled: true,
      },
      {
        key: 'Other admin actions',
        value: 'Notify when other admins take action on your investigations',
        toggle: true,
        toggled: true,
      },
      {
        key: 'Weekly performance summary',
        value: 'Internal performance metrics, sent Monday 8:00 AM',
        toggle: true,
        toggled: true,
      },
      {
        key: 'Marketing & product updates',
        value: 'Atlas product news, occasional',
        toggle: true,
        toggled: false,
      },
      {
        key: 'Browser push notifications',
        value: 'Real-time alerts in your browser',
        toggle: true,
        toggled: false,
      },
    ],
  },
  {
    id: 'sessions',
    title: 'Sessions',
    icon: 'sessions',
    meta: '2 active',
    rows: [
      {
        key: 'Idle timeout',
        value: 'Detroit, MI · Chrome · 71.82.45.12 · since 9:15 AM today',
        badge: 'This session',
        action: '1 hour',
        actionId: 'change-timeout',
      },
      {
        key: 'Other active session',
        value: 'Detroit, MI · Safari (mobile) · 173.245.45.12 · since Apr 28',
        action: 'Sign out',
        actionId: 'signout-other',
        actionDanger: true,
      },
      {
        key: 'Sign out of all sessions',
        value: 'Will require re-authentication on every device',
        action: 'Sign out all',
        actionId: 'signout-all',
        actionDanger: true,
        valueDanger: true,
      },
    ],
  },
] as const;
