import {
  DashboardNavIcon,
  CandidatesNavIcon,
  ClientsNavIcon,
  TalentSpecialistsNavIcon,
  ManagerNavIcon,
  OtherAdminsNavIcon,
  ActiveEngagementsNavIcon,
  ReviewsNavIcon,
  ReportsAnalyticsNavIcon,
  AlertTriangleIcon,
  FraudAbuseNavIcon,
  SecurityIncidentsNavIcon,
  SuspiciousActivityNavIcon,
  SuspensionsNavIcon,
  TransactionsNavIcon,
  FeesNavIcon,
  RefundsNavIcon,
  SubscriptionsNavIcon,
  TaxNavIcon,
  LegalRequestsNavIcon,
  DataSubjectRightsNavIcon,
  AuditLogsNavIcon,
  LockIcon,
  RegulatoryNavIcon,
  SettingsIcon,
  CategoriesNavIcon,
  IntegrationsNavIcon,
  EmailSmsNavIcon,
  HelpContentNavIcon,
  PerformanceNavIcon,
  IncidentReportsNavIcon,
  CommunicationsNavIcon,
  KnowledgeBaseNavIcon,
} from '@/components/ui/icons';

export const SIDEBAR_NAV = {
  topLevel: {
    id: 'dashboard',
    label: 'Dashboard',
    pathname: '/admin/dashboard',
    icon: DashboardNavIcon,
  },
  groups: [
    {
      groupId: 'users',
      label: 'Users',
      collapsedByDefault: false,
      items: [
        {
          id: 'candidates',
          label: 'Candidates',
          pathname: '/admin/users/candidates',
          icon: CandidatesNavIcon,
          count: '22.1K',
        },
        {
          id: 'clients',
          label: 'Clients',
          pathname: '/admin/users/clients',
          icon: ClientsNavIcon,
          count: '6.2K',
        },
        {
          id: 'specialists',
          label: 'Talent Specialists',
          pathname: '/admin/users/specialists',
          icon: TalentSpecialistsNavIcon,
          count: '11',
        },
        {
          id: 'manager',
          label: 'Manager',
          pathname: '/admin/users/managers',
          icon: ManagerNavIcon,
          count: '1',
        },
        {
          id: 'admins',
          label: 'Other Admins',
          pathname: '/admin/users#admins',
          icon: OtherAdminsNavIcon,
          count: '5',
        },
      ],
    },
    {
      groupId: 'operations',
      label: 'Operations',
      collapsedByDefault: false,
      items: [
        {
          id: 'engagements',
          label: 'Active Engagements',
          pathname: '#engagements',
          icon: ActiveEngagementsNavIcon,
        },
        {
          id: 'jobs',
          label: 'Job Postings',
          pathname: '#job-postings',
          icon: ClientsNavIcon,
        },
        {
          id: 'disputes',
          label: 'Disputes',
          pathname: '#disputes',
          icon: AlertTriangleIcon,
          count: '47',
          countType: 'urgent',
        },
        {
          id: 'reviews',
          label: 'Reviews',
          pathname: '#reviews',
          icon: ReviewsNavIcon,
        },
        {
          id: 'reports',
          label: 'Reports & Analytics',
          pathname: '#reports',
          icon: ReportsAnalyticsNavIcon,
        },
      ],
    },
    {
      groupId: 'trust',
      label: 'Trust & Safety',
      collapsedByDefault: false,
      items: [
        {
          id: 'fraud',
          label: 'Fraud & Abuse',
          pathname: '#fraud',
          icon: FraudAbuseNavIcon,
          count: '5',
          countType: 'urgent',
        },
        {
          id: 'incidents',
          label: 'Security Incidents',
          pathname: '#security-incidents',
          icon: SecurityIncidentsNavIcon,
        },
        {
          id: 'suspicious',
          label: 'Suspicious Activity',
          pathname: '#suspicious-activity',
          icon: SuspiciousActivityNavIcon,
          count: '3',
          countType: 'warn',
        },
        {
          id: 'suspensions',
          label: 'Suspensions & Bans',
          pathname: '#suspensions',
          icon: SuspensionsNavIcon,
        },
      ],
    },
    {
      groupId: 'finance',
      label: 'Finance',
      collapsedByDefault: false,
      items: [
        {
          id: 'transactions',
          label: 'Transactions',
          pathname: '#transactions',
          icon: TransactionsNavIcon,
        },
        {
          id: 'fees',
          label: 'Fees & Pricing',
          pathname: '#fees',
          icon: FeesNavIcon,
        },
        {
          id: 'refunds',
          label: 'Refunds',
          pathname: '#refunds',
          icon: RefundsNavIcon,
          count: '8',
          countType: 'warn',
        },
        {
          id: 'subscriptions',
          label: 'Subscriptions',
          pathname: '#subscriptions',
          icon: SubscriptionsNavIcon,
        },
        {
          id: 'tax',
          label: 'Tax Documents',
          pathname: '#tax',
          icon: TaxNavIcon,
        },
      ],
    },
    {
      groupId: 'compliance',
      label: 'Compliance',
      collapsedByDefault: false,
      items: [
        {
          id: 'legal',
          label: 'Legal Requests',
          pathname: '#legal',
          icon: LegalRequestsNavIcon,
          count: '1',
          countType: 'urgent',
        },
        {
          id: 'dsr',
          label: 'Data Subject Rights',
          pathname: '#data-subject-rights',
          icon: DataSubjectRightsNavIcon,
          count: '3',
          countType: 'warn',
        },
        {
          id: 'audit',
          label: 'Audit Logs',
          pathname: '#audit-logs',
          icon: AuditLogsNavIcon,
        },
        {
          id: 'privacy',
          label: 'Privacy Reports',
          pathname: '#privacy',
          icon: LockIcon,
        },
        {
          id: 'regulatory',
          label: 'Regulatory',
          pathname: '#regulatory',
          icon: RegulatoryNavIcon,
        },
      ],
    },
    {
      groupId: 'platform',
      label: 'Platform',
      collapsedByDefault: true,
      items: [
        {
          id: 'settings',
          label: 'Settings',
          pathname: '#settings',
          icon: SettingsIcon,
        },
        {
          id: 'categories',
          label: 'Categories & Skills',
          pathname: '#categories',
          icon: CategoriesNavIcon,
        },
        {
          id: 'integrations',
          label: 'Integrations',
          pathname: '#integrations',
          icon: IntegrationsNavIcon,
        },
        {
          id: 'email-sms',
          label: 'Email & SMS',
          pathname: '#email-sms',
          icon: EmailSmsNavIcon,
        },
        {
          id: 'help-content',
          label: 'Help Content',
          pathname: '#help-content',
          icon: HelpContentNavIcon,
        },
      ],
    },
    {
      groupId: 'internal',
      label: 'Internal',
      collapsedByDefault: true,
      items: [
        {
          id: 'performance',
          label: 'Performance',
          pathname: '#performance',
          icon: PerformanceNavIcon,
        },
        {
          id: 'incidents',
          label: 'Incident Reports',
          pathname: '#incident-reports',
          icon: IncidentReportsNavIcon,
          count: '2',
        },
        {
          id: 'communications',
          label: 'Communications',
          pathname: '#communications',
          icon: CommunicationsNavIcon,
        },
        {
          id: 'knowledge-base',
          label: 'Knowledge Base',
          pathname: '#knowledge-base',
          icon: KnowledgeBaseNavIcon,
        },
      ],
    },
  ],
  footer: {
    avatarInitials: 'AO',
    name: 'Aïsha Okafor',
    role: 'Operations Admin',
  },
} as const;
